---
title: "Untitled"
author: "楊佩雯"
date: "2017/8/4"
output: html_document
---
# 來挑變數
```{r}
# names(final)
# fit <- lm(final$戶均用電 ~ 人口數+青少年人口+壯年人口+青少年比例+壯年比例+納稅單位+綜合所得總額+平均數+第一分位數+標準差+med+大學以下比例+大學比例+碩士比例+博士比例+平均屋齡+平均坪數+公園數+公園坪數+設有戶籍宅數.宅..x+X1人一宅宅數比例...+X2人一宅宅數比例...+X3人一宅宅數比例...+X4人一宅宅數比例...+X5人一宅宅數比例...+
#             X6人以上一宅宅數比例...+有偶比例...+喪偶比例...+離婚比例...+未婚比例...+每戶平均人數+每戶平均老年人口數.人.+無老年人口戶數比例...+一位老年人口戶數.戶., data=final)
# summary(fit) # show results
# coefficients(fit)
# predict = step(fit, direction = "backward", trace=FALSE ) 
# a = predict$coefficients %>% names()  
# 
# predict = step(fit, direction = "forward", trace=FALSE ) 
# b = predict$coefficients %>% names()

# 看backward和forward挑出來的共同變數有哪些
# intersect(b,a)
```

# 挑出上述步驟選出的變數，整理一下
```{r}
final4 %>% select(青少年比例,壯年比例,綜合所得總額,標準差,med,大學以下比例,大學比例,碩士比例,博士比例,平均屋齡,平均坪數,公園數,公園坪數,商家數,X1人一宅宅數比例...,X2人一宅宅數比例...,X5人一宅宅數比例...,X6人以上一宅宅數比例...,每戶平均人數,每戶平均老年人口數.人.,無老年人口戶數比例...,一位老年人口戶數.戶.) ->gogocluster
#gogocluster<-final[,c(12,20,22,29:32,35:38,42,44,46,48,50,52,100,102,104,108,113:115)]
gogocluster$商家數[is.na(gogocluster$商家數)]<-0
#把NA用平均數補起來，才能跑分群
gogocluster$med[is.na(gogocluster$med)]<-mean(gogocluster$med,na.rm = T)
gogocluster$平均坪數[is.na(gogocluster$平均坪數)]<-mean(gogocluster$平均坪數,na.rm = T)
a<-mean(gogocluster$平均屋齡,na.rm = T)
gogocluster$平均屋齡[is.nan(gogocluster$平均屋齡)]<-a
gogocluster$平均屋齡[is.na(gogocluster$平均屋齡)]<-a
```

# 階層式分群看要分幾群
```{r}
library(cluster)
centered.x <- scale(gogocluster,center=TRUE,scale=TRUE)
x<-daisy(centered.x, stand=T)
agn<-agnes(x,metric="euclidean",method="ward")
plot(agn,ask=T)
agn$ac
wine$single<-wine[,1][agn$order]
table(wine$class.id,wine$single)

agn<-agnes(x,metric="euclidean",method="single")
plot(agn,ask=T)

agn<-agnes(x,metric="euclidean",method="complete")
plot(agn,ask=T)

agn<-agnes(x,metric="euclidean",method="average")
plot(agn,ask=T)
```

# k-means
```{r}
k.cl <- kmeans(centered.x , centers=5,nstart = 2000)
centered.x<-data.frame(centered.x)
centered.x$cluster<-k.cl$cluster
table(k.cl$cluster)
```

# 找每一群的outlier，看浪費電與非浪費電的人是誰
```{r}
final4 %>% select(戶均用電,gen_sum,人口數,青少年人口,壯年人口,青少年比例,壯年比例,納稅單位,綜合所得總額,平均數,第一分位數,標準差,med,大學以下比例,大學比例,碩士比例,博士比例,平均屋齡,平均坪數,公園數,公園坪數,設有戶籍宅數.宅..x,X1人一宅宅數比例...,X2人一宅宅數比例...,X3人一宅宅數比例...,X4人一宅宅數比例...,X5人一宅宅數比例...,X6人以上一宅宅數比例...,有偶比例...,喪偶比例...,離婚比例...,未婚比例...,每戶平均人數,每戶平均老年人口數.人.,無老年人口戶數比例...,一位老年人口戶數.戶.)->okc

okc[okc$cluster==1,c(1,3)] ->c1 
library(car)
Boxplot(c1$戶均用電, id.method="y")
```

# 建立決策樹，找到這浪費電的人的特徵
```{r}
library(rpart) 
fish.control<-rpart.control(minisplit=10,minbucket=3,xval=0)#minisplit就是node #minbucket就是葉子裡面要有幾個
fish.treeorig<-rpart(cluster~.,data=centered.x,method="class",control=fish.control) 
library(rpart.plot) 
par(family="STHeitiTC-Light")
prp(fish.treeorig,         # 模型
    faclen=0,           # 呈現的變數不要縮寫
    fallen.leaves=TRUE, # 讓樹枝以垂直方式呈現
    shadow.col="gray",  # 最下面的節點塗上陰影
    # number of correct classifications / number of observations in that node
    extra=2)  
fish.treeorig$cptable
```







